2024-11-14 14:38:51 - INFO - Запуск бота...
2024-11-14 14:38:51 - INFO - База данных инициализирована
2024-11-14 14:38:51 - INFO - AuthHandler инициализирован
2024-11-14 14:38:52 - INFO - Приложение создано с токеном: 7892353308...
2024-11-14 14:38:52 - INFO - Добавление обработчика конверсации
2024-11-14 14:38:52 - INFO - Запуск процесса поллинга
2024-11-14 14:38:57 - DEBUG - Вызвана команда start пользователем 6121074409
2024-11-14 14:38:57 - DEBUG - Отправлено стартовое меню
2024-11-14 14:39:13 - ERROR - Произошла ошибка: 'DatabaseHandler' object has no attribute 'get_store_employees'
2024-11-14 14:39:13 - ERROR - 'DatabaseHandler' object has no attribute 'get_store_employees'
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 685, in show_employees_list
    employees = self.db.get_store_employees(store_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DatabaseHandler' object has no attribute 'get_store_employees'
