2024-11-14 15:40:40 - INFO - Запуск бота...
2024-11-14 15:40:40 - INFO - База данных инициализирована
2024-11-14 15:40:40 - INFO - AuthHandler инициализирован
2024-11-14 15:40:41 - INFO - Приложение создано с токеном: 7892353308...
2024-11-14 15:40:41 - INFO - Добавление обработчика конверсации
2024-11-14 15:40:41 - INFO - Запуск процесса поллинга
2024-11-14 15:40:55 - DEBUG - Вызвана команда start пользователем 6121074409
2024-11-14 15:40:55 - DEBUG - Отправлено стартовое меню
2024-11-14 15:40:58 - DEBUG - Получен штрих-код: 80004370
2024-11-14 15:41:11 - ERROR - Произошла ошибка: 'DatabaseHandler' object has no attribute 'conn'
2024-11-14 15:41:11 - ERROR - 'DatabaseHandler' object has no attribute 'conn'
Traceback (most recent call last):
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 1319, in process_update
    await coroutine
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 844, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        update, application, handler_check_result, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\anxiety\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 158, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\handlers\auth_handler.py", line 427, in handle_position_selection
    self.db.remove_all_admin_stores(user_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\anxiety\.cursor-tutor\database\db_handler.py", line 271, in remove_all_admin_stores
    with self.conn:
         ^^^^^^^^^
AttributeError: 'DatabaseHandler' object has no attribute 'conn'
